<a href="https://colab.research.google.com/github/LAlejandro8/tutorial-numpy/blob/master/tutorial_numpy_pl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

a = np.arange(4)

print("a = ", a)
print("a + 5", a + 5)
print("a - 5 ", a - 5)
print("a * 2 ", a * 2)
print("a / 2", a / 2)
print("a // 2", a // 2)
print("-a = ", -a)
print("a ** 2 ", a ** 2)
print("a % 2 ", a % 2)

a =  [0 1 2 3]
a + 5 [5 6 7 8]
a - 5  [-5 -4 -3 -2]
a * 2  [0 2 4 6]
a / 2 [0.  0.5 1.  1.5]
a // 2 [0 0 1 1]
-a =  [ 0 -1 -2 -3]
a ** 2  [0 1 4 9]
a % 2  [0 1 0 1]


In [4]:
a = np.arange(4)
b = np.arange(1, 5)

display(np.exp(a))        # Exponencial
display(np.log(b))        # Logaritmo natural
display(np.sqrt(a))       # Raiz cuadrada
display(np.greater(a,b))  # Superior o igual, punto a punto

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])

In [7]:
# %%timeit Toma el tiempo de ejecución en velocidad python
%%timeit
a = np.arange(1000000)
b = np.zeros(1000000)
i = 0
for el in a:
    b[i] = el+el
    i+=1

1 loop, best of 3: 305 ms per loop


In [8]:
# Toma el tiempo de ejecucion en velocidad C de lo mismo que se hizo en el punto anterior
%%timeit
a+a

The slowest run took 77.77 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 505 ns per loop


**Estadística y aletoriedad**

In [9]:
# Estadística
a = np.arange(10)

display(np.mean(a))   # Promedio
display(np.median(a)) # Mediana

4.5

4.5

In [10]:
np.percentile(a,10) # Percentil, en este caso queremos el percentil No. 10

0.9

In [13]:
# Aletoriedad

np.random.random(10)

array([0.11524332, 0.91661411, 0.2478343 , 0.21472465, 0.35371558,
       0.57701151, 0.89292217, 0.18201665, 0.38216701, 0.42140385])